import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { type FormEvent, useEffect, useState } from "react";
import { api } from "../api/client";
import type { Equipment, Profile } from "../api/types";

function commaList(value: string): string[] {
  return value.split(",").map((item) => item.trim()).filter(Boolean);
}

export function SettingsPage() {
  const queryClient = useQueryClient();
  const profile = useQuery({ queryKey: ["profile"], queryFn: () => api<Profile>("/profile") });
  const equipment = useQuery({ queryKey: ["equipment"], queryFn: () => api<Equipment[]>("/equipment") });
  const runtime = useQuery({ queryKey: ["runtime-settings"], queryFn: () => api<Record<string, string | boolean | number>>("/settings") });
  const [form, setForm] = useState<Partial<Profile>>({});
  const [createdToken, setCreatedToken] = useState("");
  useEffect(() => { if (profile.data) setForm(profile.data); }, [profile.data]);
  const save = useMutation({ mutationFn: () => api<Profile>("/profile", { method: "PATCH", body: JSON.stringify(form) }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["profile"] }) });
  const equipmentUpdate = useMutation({ mutationFn: ({ id, available }: { id: string; available: boolean }) => api<Equipment>(`/equipment/${id}`, { method: "PATCH", body: JSON.stringify({ available }) }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["equipment"] }) });
  const token = useMutation({ mutationFn: () => api<{ token: string }>("/auth/tokens?name=Chrome%20extension", { method: "POST" }), onSuccess: (data) => setCreatedToken(data.token) });
  function submit(event: FormEvent) { event.preventDefault(); save.mutate(); }
  if (!profile.data) return <div className="loading">Loading settings...</div>;
  const strength = form.strength_capacity_json ?? {};
  const bench = (strength.bench_press as Record<string, unknown> | undefined) ?? {};
  const pullUp = (strength.strict_pull_up as Record<string, unknown> | undefined) ?? {};
  const endurance = form.endurance_capacity_json ?? {};
  const running = (endurance.running as Record<string, unknown> | undefined) ?? {};
  const runGoal = (running.goal_distance_km as number[] | undefined) ?? [8, 12];
  const nutrition = form.nutrition_preferences ?? {};
  const proteinRange = (nutrition.protein_range_g as number[] | undefined) ?? [145, 170];
  return <><header className="page-header"><div><p className="eyebrow">Your constraints and preferences</p><h1>Settings</h1></div></header>
    <form className="settings-grid" onSubmit={submit}><section className="card"><p className="eyebrow">Profile</p><div className="form-grid"><label>Location<input value={form.location ?? ""} onChange={(event) => setForm({ ...form, location: event.target.value })} /></label><label>Timezone<input value={form.timezone ?? ""} onChange={(event) => setForm({ ...form, timezone: event.target.value })} /></label><label>Weight kg<input type="number" value={form.weight_kg ?? ""} onChange={(event) => setForm({ ...form, weight_kg: Number(event.target.value) })} /></label><label>Height cm<input type="number" value={form.height_cm ?? ""} onChange={(event) => setForm({ ...form, height_cm: Number(event.target.value) })} /></label><label>Age, optional<input type="number" value={form.age ?? ""} onChange={(event) => setForm({ ...form, age: Number(event.target.value) || null })} /></label><label>Sex, optional<input value={form.sex ?? ""} onChange={(event) => setForm({ ...form, sex: event.target.value || null })} /></label></div><label>Primary training goal<textarea value={form.primary_training_goal ?? ""} onChange={(event) => setForm({ ...form, primary_training_goal: event.target.value })} /></label><label>Body-composition direction<textarea value={form.body_composition_goal ?? ""} onChange={(event) => setForm({ ...form, body_composition_goal: event.target.value || null })} /></label><button className="primary" disabled={save.isPending}>Save settings</button>{save.isSuccess && <span className="success">Saved</span>}{save.error && <p className="error">{save.error.message}</p>}</section>
      <section className="card"><p className="eyebrow">Planning rules</p><div className="form-grid"><label>Maximum main meals<input type="number" min="1" max="2" value={form.max_main_meals_per_day ?? 2} onChange={(event) => setForm({ ...form, max_main_meals_per_day: Number(event.target.value) })} /></label><label>Preferred main meals<input type="number" min="1" max="2" value={form.preferred_main_meals_per_day ?? 2} onChange={(event) => setForm({ ...form, preferred_main_meals_per_day: Number(event.target.value) })} /></label><label>Maximum exercises<input type="number" min="1" max="3" value={form.max_exercises_per_day ?? 3} onChange={(event) => setForm({ ...form, max_exercises_per_day: Number(event.target.value) })} /></label><label>Thursday commute minutes<input type="number" min="0" value={Number(nutrition.thursday_commute_minutes ?? 180)} onChange={(event) => setForm({ ...form, nutrition_preferences: { ...nutrition, thursday_commute_minutes: Number(event.target.value) } })} /></label></div><label>Gym days, comma separated<input value={(form.gym_days ?? []).join(", ")} onChange={(event) => setForm({ ...form, gym_days: commaList(event.target.value) })} /></label><label>Office days, comma separated<input value={(form.office_days ?? []).join(", ")} onChange={(event) => setForm({ ...form, office_days: commaList(event.target.value) })} /></label><label>Excluded exercises, comma separated<input value={(form.excluded_exercises ?? []).join(", ")} onChange={(event) => setForm({ ...form, excluded_exercises: commaList(event.target.value) })} /></label><label>Allergies, comma separated<input value={(form.allergies ?? []).join(", ")} onChange={(event) => setForm({ ...form, allergies: commaList(event.target.value) })} /></label><label>Medical constraints, comma separated<input value={(form.medical_constraints ?? []).join(", ")} onChange={(event) => setForm({ ...form, medical_constraints: commaList(event.target.value) })} /></label></section>
      <section className="card"><p className="eyebrow">Current capacity</p><div className="form-grid"><label>Bench press load kg<input type="number" min="0" value={Number(bench.load_kg ?? 100)} onChange={(event) => setForm({ ...form, strength_capacity_json: { ...strength, bench_press: { ...bench, load_kg: Number(event.target.value) } } })} /></label><label>Strict pull-ups<input value={String(pullUp.reps ?? ">10")} onChange={(event) => setForm({ ...form, strength_capacity_json: { ...strength, strict_pull_up: { ...pullUp, reps: event.target.value } } })} /></label><label>Running goal minimum km<input type="number" min="0" value={runGoal[0]} onChange={(event) => setForm({ ...form, endurance_capacity_json: { ...endurance, running: { ...running, goal_distance_km: [Number(event.target.value), runGoal[1]] } } })} /></label><label>Running goal maximum km<input type="number" min="0" value={runGoal[1]} onChange={(event) => setForm({ ...form, endurance_capacity_json: { ...endurance, running: { ...running, goal_distance_km: [runGoal[0], Number(event.target.value)] } } })} /></label><label>Cycling FTP watts, optional<input type="number" min="0" value={Number(endurance.cycling_ftp_watts ?? 0) || ""} onChange={(event) => setForm({ ...form, endurance_capacity_json: { ...endurance, cycling_ftp_watts: Number(event.target.value) || null } })} /></label><label>Protein target minimum g<input type="number" min="0" value={proteinRange[0]} onChange={(event) => setForm({ ...form, nutrition_preferences: { ...nutrition, protein_range_g: [Number(event.target.value), proteinRange[1]] } })} /></label><label>Protein target maximum g<input type="number" min="0" value={proteinRange[1]} onChange={(event) => setForm({ ...form, nutrition_preferences: { ...nutrition, protein_range_g: [proteinRange[0], Number(event.target.value)] } })} /></label></div></section>
      <section className="card"><p className="eyebrow">Available equipment</p>{equipment.data?.map((item) => <label className="equipment-row" key={item.id}><input type="checkbox" checked={item.available} onChange={(event) => equipmentUpdate.mutate({ id: item.id, available: event.target.checked })} />{item.name}</label>)}</section>
      <section className="card"><p className="eyebrow">Recommended kitchen additions</p>{(form.kitchen_equipment_json ?? []).map((item) => <label className="equipment-row" key={item.name}><input type="checkbox" checked={item.owned === true} onChange={(event) => setForm({ ...form, kitchen_equipment_json: form.kitchen_equipment_json?.map((candidate) => candidate.name === item.name ? { ...candidate, owned: event.target.checked } : candidate) })} />{item.name}</label>)}</section>
      <section className="card"><p className="eyebrow">Integrations</p><div className="rule-list">{Object.entries(runtime.data ?? {}).map(([key, value]) => <div key={key}><span>{key.replaceAll("_", " ")}</span><strong>{String(value)}</strong></div>)}</div><hr /><h3>Chrome extension token</h3><p>Generate a revocable token and paste it into the extension. It is shown only once.</p><button type="button" className="quiet" onClick={() => token.mutate()}>Generate token</button>{createdToken && <code className="token-output">{createdToken}</code>}</section>
    </form></>;
}
