"""initial schema

Revision ID: 123e13254a6c
Revises: 
Create Date: 2026-08-09 15:46:35.626384
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '123e13254a6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('message_date', sa.Date(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('proposal_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message'))
    )
    op.create_index(op.f('ix_chat_message_message_date'), 'chat_message', ['message_date'], unique=False)
    op.create_table('equipment',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment')),
    sa.UniqueConstraint('name', name=op.f('uq_equipment_name'))
    )
    op.create_table('exercise',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('equipment_required', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gym_only', sa.Boolean(), nullable=False),
    sa.Column('compound', sa.Boolean(), nullable=False),
    sa.Column('measurement_type', sa.String(length=40), nullable=False),
    sa.Column('pain_exclusion_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise')),
    sa.UniqueConstraint('name', name=op.f('uq_exercise_name'))
    )
    op.create_table('food_item',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('protein_g_per_100', sa.Float(), nullable=True),
    sa.Column('carbs_g_per_100', sa.Float(), nullable=True),
    sa.Column('fat_g_per_100', sa.Float(), nullable=True),
    sa.Column('fiber_g_per_100', sa.Float(), nullable=True),
    sa.Column('calories_per_100', sa.Float(), nullable=True),
    sa.Column('typical_unit', sa.String(length=40), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('freezer_friendly', sa.Boolean(), nullable=False),
    sa.Column('retailer_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_item')),
    sa.UniqueConstraint('name', name=op.f('uq_food_item_name'))
    )
    op.create_table('meal_template',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ingredients_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('hands_on_minutes', sa.Integer(), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('fridge_life_days', sa.Integer(), nullable=True),
    sa.Column('freezer_friendly', sa.Boolean(), nullable=False),
    sa.Column('reheat_method', sa.String(length=160), nullable=True),
    sa.Column('estimated_protein_g', sa.Float(), nullable=False),
    sa.Column('estimated_fiber_g', sa.Float(), nullable=False),
    sa.Column('produce_portions', sa.Float(), nullable=False),
    sa.Column('effort_score', sa.Integer(), nullable=False),
    sa.Column('preference_score', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_template')),
    sa.UniqueConstraint('name', name=op.f('uq_meal_template_name'))
    )
    op.create_table('notification_event',
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_event')),
    sa.UniqueConstraint('event_type', 'event_date', name=op.f('uq_notification_event_event_type'))
    )
    op.create_index(op.f('ix_notification_event_event_date'), 'notification_event', ['event_date'], unique=False)
    op.create_table('nutrition_entry',
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('meal_slot', sa.String(length=40), nullable=False),
    sa.Column('planned_recommendation_id', sa.String(length=80), nullable=True),
    sa.Column('food_or_meal_reference', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('expected', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition_entry')),
    sa.UniqueConstraint('entry_date', 'planned_recommendation_id', name=op.f('uq_nutrition_entry_entry_date'))
    )
    op.create_index(op.f('ix_nutrition_entry_entry_date'), 'nutrition_entry', ['entry_date'], unique=False)
    op.create_table('planning_run',
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('planner_version', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('context_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planning_run'))
    )
    op.create_index(op.f('ix_planning_run_plan_date'), 'planning_run', ['plan_date'], unique=False)
    op.create_table('profile_snapshot',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('training_status', sa.Text(), nullable=False),
    sa.Column('strength_capacity_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('endurance_capacity_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recent_training_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recent_nutrition_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recovery_status', sa.String(length=80), nullable=False),
    sa.Column('adherence_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('important_constraints_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_priorities_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('short_summary', sa.Text(), nullable=False),
    sa.Column('detailed_summary', sa.Text(), nullable=False),
    sa.Column('source_quality_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_snapshot'))
    )
    op.create_index(op.f('ix_profile_snapshot_snapshot_date'), 'profile_snapshot', ['snapshot_date'], unique=False)
    op.create_table('shopping_plan',
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('retailer', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('estimated_total_chf', sa.Float(), nullable=False),
    sa.Column('items_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_plan')),
    sa.UniqueConstraint('week_start', 'retailer', 'mode', name=op.f('uq_shopping_plan_week_start'))
    )
    op.create_index(op.f('ix_shopping_plan_week_start'), 'shopping_plan', ['week_start'], unique=False)
    op.create_table('user_account',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account'))
    )
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=True)
    op.create_table('api_token',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_account.id'], name=op.f('fk_api_token_account_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_token'))
    )
    op.create_index(op.f('ix_api_token_token_hash'), 'api_token', ['token_hash'], unique=True)
    op.create_table('daily_plan',
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('profile_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('planning_run_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('short_summary', sa.Text(), nullable=False),
    sa.Column('original_plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['planning_run_id'], ['planning_run.id'], name=op.f('fk_daily_plan_planning_run_id_planning_run')),
    sa.ForeignKeyConstraint(['profile_snapshot_id'], ['profile_snapshot.id'], name=op.f('fk_daily_plan_profile_snapshot_id_profile_snapshot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_plan')),
    sa.UniqueConstraint('plan_date', name=op.f('uq_daily_plan_plan_date'))
    )
    op.create_index(op.f('ix_daily_plan_plan_date'), 'daily_plan', ['plan_date'], unique=False)
    op.create_table('inventory_item',
    sa.Column('food_item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_estimate', sa.Float(), nullable=True),
    sa.Column('quantity_label', sa.String(length=80), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_item.id'], name=op.f('fk_inventory_item_food_item_id_food_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_item')),
    sa.UniqueConstraint('food_item_id', name=op.f('uq_inventory_item_food_item_id'))
    )
    op.create_table('user_profile',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=40), nullable=True),
    sa.Column('body_composition_goal', sa.Text(), nullable=True),
    sa.Column('primary_training_goal', sa.Text(), nullable=False),
    sa.Column('max_main_meals_per_day', sa.Integer(), nullable=False),
    sa.Column('preferred_main_meals_per_day', sa.Integer(), nullable=False),
    sa.Column('max_exercises_per_day', sa.Integer(), nullable=False),
    sa.Column('gym_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('office_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excluded_exercises', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nutrition_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('medical_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strength_capacity_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('endurance_capacity_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kitchen_equipment_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_account.id'], name=op.f('fk_user_profile_account_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile')),
    sa.UniqueConstraint('account_id', name=op.f('uq_user_profile_account_id'))
    )
    op.create_table('web_session',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_account.id'], name=op.f('fk_web_session_account_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_session'))
    )
    op.create_index(op.f('ix_web_session_expires_at'), 'web_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_web_session_token_hash'), 'web_session', ['token_hash'], unique=True)
    op.create_table('workout_entry',
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('planned_recommendation_id', sa.String(length=80), nullable=True),
    sa.Column('exercise_id', sa.Uuid(), nullable=True),
    sa.Column('exercise_name', sa.String(length=160), nullable=False),
    sa.Column('prescription_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actual_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty_1_to_10', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('pain_flag', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_workout_entry_exercise_id_exercise')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_entry')),
    sa.UniqueConstraint('entry_date', 'planned_recommendation_id', name=op.f('uq_workout_entry_entry_date'))
    )
    op.create_index(op.f('ix_workout_entry_entry_date'), 'workout_entry', ['entry_date'], unique=False)
    op.create_table('derived_summary',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nutrition_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], name=op.f('fk_derived_summary_profile_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_derived_summary')),
    sa.UniqueConstraint('profile_id', name=op.f('uq_derived_summary_profile_id'))
    )
    op.create_table('plan_modification',
    sa.Column('daily_plan_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.String(length=80), nullable=False),
    sa.Column('original_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('replacement_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['daily_plan_id'], ['daily_plan.id'], name=op.f('fk_plan_modification_daily_plan_id_daily_plan'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_modification'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_modification')
    op.drop_table('derived_summary')
    op.drop_index(op.f('ix_workout_entry_entry_date'), table_name='workout_entry')
    op.drop_table('workout_entry')
    op.drop_index(op.f('ix_web_session_token_hash'), table_name='web_session')
    op.drop_index(op.f('ix_web_session_expires_at'), table_name='web_session')
    op.drop_table('web_session')
    op.drop_table('user_profile')
    op.drop_table('inventory_item')
    op.drop_index(op.f('ix_daily_plan_plan_date'), table_name='daily_plan')
    op.drop_table('daily_plan')
    op.drop_index(op.f('ix_api_token_token_hash'), table_name='api_token')
    op.drop_table('api_token')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_index(op.f('ix_shopping_plan_week_start'), table_name='shopping_plan')
    op.drop_table('shopping_plan')
    op.drop_index(op.f('ix_profile_snapshot_snapshot_date'), table_name='profile_snapshot')
    op.drop_table('profile_snapshot')
    op.drop_index(op.f('ix_planning_run_plan_date'), table_name='planning_run')
    op.drop_table('planning_run')
    op.drop_index(op.f('ix_nutrition_entry_entry_date'), table_name='nutrition_entry')
    op.drop_table('nutrition_entry')
    op.drop_index(op.f('ix_notification_event_event_date'), table_name='notification_event')
    op.drop_table('notification_event')
    op.drop_table('meal_template')
    op.drop_table('food_item')
    op.drop_table('exercise')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_chat_message_message_date'), table_name='chat_message')
    op.drop_table('chat_message')
    # ### end Alembic commands ###

