"""add daily food logs

Revision ID: 2adc3fa0e305
Revises: 123e13254a6c
Create Date: 2026-08-09 16:59:29.217658
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2adc3fa0e305'
down_revision: Union[str, None] = '123e13254a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_food_log',
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('extraction_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_food_log')),
    sa.UniqueConstraint('log_date', name=op.f('uq_daily_food_log_log_date'))
    )
    op.create_index(op.f('ix_daily_food_log_log_date'), 'daily_food_log', ['log_date'], unique=False)
    op.add_column('nutrition_entry', sa.Column('food_log_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_nutrition_entry_food_log_id'), 'nutrition_entry', ['food_log_id'], unique=False)
    op.create_foreign_key(op.f('fk_nutrition_entry_food_log_id_daily_food_log'), 'nutrition_entry', 'daily_food_log', ['food_log_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_nutrition_entry_food_log_id_daily_food_log'), 'nutrition_entry', type_='foreignkey')
    op.drop_index(op.f('ix_nutrition_entry_food_log_id'), table_name='nutrition_entry')
    op.drop_column('nutrition_entry', 'food_log_id')
    op.drop_index(op.f('ix_daily_food_log_log_date'), table_name='daily_food_log')
    op.drop_table('daily_food_log')
    # ### end Alembic commands ###

